#!/bin/bash
function usage {
  echo "Usage: ./ansible-dev PLAYBOOKNAME *extra_args"
}

playbook="$1"
extra_args="${@:2}"

if [ -z "$playbook" ]
then
  usage
  exit 1
fi

# Assume machine name is same as playbookname - '.yml'.
machine_name=${playbook%%\.yml}

ansible-playbook -i inv/development --private-key "`pwd`/.vagrant/machines/${machine_name}/virtualbox/private_key" -u vagrant "$@"
