# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vbguest.auto_update = true

  config.vm.box = "debian/jessie64"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.define "opennebula" do |machine|
    machine.vm.network :private_network, ip: "192.168.111.170"
    machine.vm.provision :ansible do |ansible|
      ansible.playbook = "opennebula.yml"
      ansible.inventory_path = "inv/development"
    end
  end

  config.vm.define "useradmin" do |machine|
    machine.vm.network :private_network, ip: "192.168.111.171"
    machine.vm.provision :ansible do |ansible|
      ansible.playbook = "useradmin.yml"
      ansible.inventory_path = "inv/development"
    end
    machine.vm.synced_folder '../useradmin/', '/var/www/useradmin/current', owner: "surfsara", group: "surfsara"
  end
end
