source 'https://rubygems.org'


gem 'rails', '5.0.0.1'
gem 'pg'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'therubyracer', platforms: :ruby
gem 'jquery-rails'
gem 'turbolinks'
gem 'slim-rails'
gem "trailblazer"
gem "trailblazer-rails"
gem 'opennebula'
gem 'email_validator'

group :development, :test do
  gem 'byebug'
  gem 'rspec-rails'
  gem 'rspec-its'
  gem 'webmock'
  gem 'vcr'
  gem 'simplecov', require: false
  gem 'capybara', require: false
  gem 'capybara-webkit', require: false
  gem 'capybara-screenshot', require: false
  gem 'timecop'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'pry'
  gem 'letter_opener'
  gem 'better_errors'
  gem 'binding_of_caller'
end
